### ISSUE TITLE
Summary of the CoP Validated Content Candidate Submission Review

### ISSUE THREAD

**Issue by alisonlhart** [ansible-middleware/common_criteria_demo#1]
Summary of the Community of Practice (CoP) Validated Content Candidate Submission review from April 5, 2023:

- The content is not a collection as there is no `galaxy.yml` file. This prevents the content from being imported by Galaxy or Private Automation Hub. 
- The business value isn't currently present for this particular content, since the content is primarily just two playbooks, and customers could copy these playbooks for use without integration. 
- The included playbooks do not use roles from the `common_criteria` collection.
- The name demo and the content indicates that the content is for demonstration purposes only and does not have production usage value, which is crucial for acceptance as Validated Content. 
Note: The `common_criteria` collection may be a good candidate for Validated Content. 

For more discussion on this, you can tag the AnsiblePartners team (@alisonlhart, @thedoubl3j, @cross-logic), or you can close this issue.

**Comment by rpelisse** [comment]
@RanabirChakraborty Can you update the playbooks to use the content of the converge.yml ? In the converge, simply import the appropriate playbooks, it will avoid code duplication. 
 
Can you look into submitting the common_criteria collection, as suggested by @alisonlhart ?
